gui:
  scrollHeight: 3
  expandFocusedSidePanel: true
  theme:
    inactiveBorderColor:
      - blue
  authorColors:
    # use green for nikolas
    "NikoKS": "#a3be8c"
    "nikolasetiawan": "#a3be8c"
    # use blue for other authors
    "*": "#81a1c1"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  edit: '[ -z "$NVIM" ] && (nvim -- {{filename}}) || (nvim --server "$NVIM" --remote-send "<C-\><C-N>:q!<CR>" && nvim --server "$NVIM" --remote {{filename}})'
  editInTerminal: true
  openCommand: ""
quitOnTopLevelReturn: true
promptToReturnFromSubprocess: false
notARepository: "skip"
keybinding:
  universal:
    gotoTop: "g"
    gotoBottom: "G"
    goInto: "<space>"
    select: "<enter>"
  commits:
    checkoutCommit: "<enter>"
    viewResetOptions: "r"
    renameCommit: ""
  stash:
    popStash: "p"
# customCommands:
#   - key: "o"
#     context: "commitFiles"
#     command: "nvim --server $NVIM --remote-send 'q'; nvim --server $NVIM --remote-send ':Gedit {{.SelectedLocalCommit.Sha}}:{{.SelectedCommitFile.Name}} <CR>'"
#     description: "open file on this commit"
