vim.cmd('unmap <buffer> [[')
vim.cmd('unmap <buffer> []')
vim.cmd('unmap <buffer> ["')
-- vim.cmd('unmap <buffer> [%')
vim.cmd('unmap <buffer> ][')
vim.cmd('unmap <buffer> ]]')
vim.cmd('unmap <buffer> ]"')
-- vim.cmd('unmap <buffer> ]%')
