# Aliases
alias e='exit'
alias c='clear'
# alias vim='lvim'
alias tmux='tmux -f $HOME/.tmux.conf'
alias t='tmux -f $HOME/.config/tmux/tmux.conf'

# Autojump
[ -f /usr/share/autojump/autojump.sh ] && . /usr/share/autojump/autojump.sh
